"""add first

Revision ID: f83e9bcc272f
Revises: 
Create Date: 2018-01-04 14:49:16.630000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83e9bcc272f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('mailaddress', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('val_date', sa.Integer(), nullable=True),
    sa.Column('holiday', sa.Integer(), nullable=True),
    sa.Column('add_day', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=10), nullable=False),
    sa.Column('approve1', sa.String(length=20), nullable=True),
    sa.Column('approve2', sa.String(length=20), nullable=True),
    sa.Column('approve3', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mailaddress')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('request_date', sa.DateTime(), nullable=False),
    sa.Column('request_time', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('request_flag', sa.Integer(), nullable=True),
    sa.Column('approve_flag', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user.mailaddress'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles')
    op.drop_table('user')
    # ### end Alembic commands ###
